"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$hhihavyjxle_rjoo&8o431*73%gd83!)nd4tz(l3e3q)okj*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django_extensions",
    "rest_framework",
    # "rest_framework.authtoken",
    "drf_spectacular",

    # 【知识点】为了弥补 Django 自带权限机制的不足
    # - Django 自带的权限机制是针对模型的，用户可以获得对所有文章对象进行修改的权限
    # - 如果我们希望实现对单个文章对象的权限管理，我们需要借助于第三方库比如 django-guardian
    # "guardian",

    "apps.core",
    "apps.blog",
    "apps.tasks",
    "apps.invitationcode",
    "apps.auth2",

    "debug_toolbar",
]

MIDDLEWARE = [
    # debug-toolbar 的中间件尽可能的往前配置
    'debug_toolbar.middleware.DebugToolbarMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 【知识点】LocaleMiddleware 属于 Django 的国际化功能，这个中间件可以让我们不需要设置 settings.LANGUAGE_CODE
    "django.middleware.locale.LocaleMiddleware",

    # "apps.core.middleware.GlobalExceptionMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 【知识点】此处需要配置全局模板目录，django 默认是去 INSTALLED_APPS 下的 templates 目录搜索，
        #  这也是为什么推荐 app 下的目录要嵌套一个 app_name 目录以避免命名冲突（应该是和全局模板目录冲突）
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# 使用 django 自带的 sqlite3 存储 session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 语言设置为简体中文

TIME_ZONE = 'Asia/Shanghai'  # 时区设置为中国标准时间（东八区）

USE_I18N = True  # 启用国际化（保持 True）

USE_TZ = False  # 关闭时区支持（适用场景：如果你的用户和服务器都在中国，且不需要处理跨国时区问题。）

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------ djangorestframework ------------------------------------ #
# drf 配置字典
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    # 返回 response 对象所用的类 -> DRF 会根据请求的 Accept 头来选择一个最合适的渲染器
    'DEFAULT_RENDER_CLASSES': [
        'rest_framework.renders.JSONRenderer',
        'rest_framework.renders.BrowsableAPIRenderer',  # DRF 一般都是 restful 风格的接口，一般这个都是开发阶段才启用的
    ],
    # 解析器，如何解析 request 请求中的 request.data
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 权限相关配置
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated', # 仅限已经通过身份验证的用户访问
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # 未经身份验证的请求将获得只读读的权限
    ],
    'UNAUTHENTICATED_USER': None,  # 未认证时不设置匿名用户
    # 认证相关配置 [reference link](https://pythondjango.cn/django/rest-framework/5-permissions/)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',

        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ],
    # "URL_FIELD_NAME": 'link', # todo: [to be understood] URL_FIELD_NAME
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # drf_spectacular 接口文档生成
    'EXCEPTION_HANDLER': 'apps.core.exceptions.global_exception_handler'
}

# ------------------------------------ python-memcached ------------------------------------ #
# 【知识点】配置缓存
#  问题：为什么要使用缓存Cache？回答：这是个通用问题，即缓存的作用（不包括 django，比如操作系统等也有）
#  参考资料：https://pythondjango.cn/django/advanced/7-cache/
# 本地缓存，使用 localhost
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         # 【知识点】此处可以拓展：分布式缓存，多台服务器，支持配置权重
#         'LOCATION': '127.0.0.1:11211',
#     }
# }

# ------------------------------------ django-debug-toolbar ------------------------------------ #
# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.versions.VersionsPanel',
#     'debug_toolbar.panels.timer.TimerPanel',
#
#     'djdt_flamegraph.FlamegraphPanel',
# ]

INTERNAL_IPS = ["127.0.0.1"]

# ------------------------------------ django-guardian ------------------------------------ #
# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.ModelBackend',
#     'guardian.backends.ObjectPermissionBackend',
# )
